### ISSUE TITLE
Change names to match Antd component names

### ISSUE THREAD

**Issue by jannikbuschke** [jannikbuschke/formik-antd#14]
In order to make migrations easier and to make the component names simpler, the *Field* suffix should be dropped. 
It's likely that in a specific files (maybe even in a codebase) only exclusively  formik-antd or antd components will be used, so the readability/comprehensibility should be granted.

**Comment by jwmann** [comment]
I agree with this; once all PR's have been merged. :)

**Comment by jwmann** [comment]
I think after we do this, we should bump up to a major version. `1.0.0`
This makes sense if we're following https://semver.org/ which seems to be a standard convention in most projects.

**Comment by jannikbuschke** [comment]
Y, I like the api and guess it will be stable for some time. So `1.0.0` is close.
The renaming is done, I also made some depending components properties of their related ones (InputPassword => Input.Password, InputTextArea => Input.TextArea, RadioGroup => Radio.Group ....)

**Comment by jwmann** [comment]
I only suggest `1.0.0` because technically this naming change will break any project that's currently using this package. ( aka not backwards compatible update )

Of course it's just a simple name change for them to fix but if they just update from `0.8.2` to `0.12.0` without thinking much, because doesn't seem too big a of jump. I wouldn't expect my project to break.

Whereas `0.8.2` to `1.0.0` you know something changed and I should check before updating the package.

It's not a super big deal because this package isn't being used by millions of people but I do think it's important.

**Comment by jannikbuschke** [comment]
But this is also semver: all 0.* versions are pre 1 and can have breaking changes. The initial/alpha phase cannot practically have a stable api and be backwards compatible...
During 1.* only additions and patches are allowed.

**Comment by jwmann** [comment]
@jannikbuschke Fair point. I'm fine with whatever then.
