### ISSUE TITLE
exposed validate prop does not have any effect

### ISSUE THREAD

**Issue by jannikbuschke** [jannikbuschke/formik-antd#34]
It seems exposing Formiks Field validate function does not have any effect. In the docs https://jaredpalmer.com/formik/docs/api/field its only used on bare Fields, so maybe it is only useful in such case.

**Comment by jannikbuschke** [comment]
has been removed

**Comment by jwmann** [comment]
Can you elaborate on this?
I use the validate function for almost every input field, how does it not have any effect?

**Comment by jannikbuschke** [comment]
I thought it is not working. I tested a bit with code like this:

`<Input name="test" validate={value=>return !value ? "required" : undefined } />`

I expected the validate function to be called whenever the value of the input component changes. However in my tests this never happened.

Can you give me some sample code to understand how it is used?

**Comment by jwmann** [comment]
That example should be working fine enough (might throw console.log in there to be sure) but keep in mind, the validation only runs for `onBlur` and it Formik does this on purpose there's a huge discussion on that in their GitHub repo issues

Also your example will only show results if there is no value.
So you'd have to do:

1) Input the letter "a"
2) Backspace (input is now empty)
3) Click out of the input (anywhere outside of the field) to trigger the `onBlur`

Validation should run.

I use this validation technique on an insanely complex form live on production right now so I can vouch that it works.

**Comment by jannikbuschke** [comment]
Weird, I am pretty sure that it didnt work for me last time. Maybe I used some component where this doesnt work?
Are you using this technique with more components other than Input?

I will revert the changes so validate will work again in the next preview.

**Comment by jwmann** [comment]
I'm using this with mainly on Input, TextArea, and Select but I've tested it on everything back when I added validate a few months ago

**Comment by jannikbuschke** [comment]
It seems that when the <Input> component is placed inside a <FormItem> component the validate handlers are not called.

**Comment by jwmann** [comment]
That's because this is not the intended way `<FormItem>` works.
`<FormItem>` does not need a validate, since it doesn't receive values, `<FormItem>` is an error handler so it only requires the name of the child Input.

Here's an example of what I mean.

```
<FormItem name="myFieldName">
  <Input 
    name="myFieldName"
    validate={v => !v ? 'required' : undefined } // Field specific validation
  />
</FormItem>
```

FormItem will use the name prop to detect any associated validation errors.
By setting `validate` on both, you're essentially overwriting the validation on the real field with one that will always return `undefined`.

**Comment by jannikbuschke** [comment]
This code doesnt seem to work for me. Whenever an Input component is wrapped in a FormItem the Inputs validate handler is not called (if the FormItem has a validate handler set it will get called).

Can you really confirm that this setup worked in the past?:
```
<FormItem name="myFieldName">
  <Input 
    name="myFieldName"
    validate={v => !v ? 'required' : undefined } // Field specific validation
  />
</FormItem>
```

**Comment by jwmann** [comment]
@jannikbuschke Yes I'm very sure this works. At least for the versions that I'm currently using.
Here is a GIF of it working - https://jwm.d.pr/QkydNY/jULzcp8QnE

![Field Validation POC](https://cdn-sec.droplr.net/files/acc_2368/QkydNY?response-content-disposition=inline%3B%20filename%3DScreen%2520Capture%2520on%25202019-05-24%2520at%252020-13-36.gif&Expires=1558743613&Key-Pair-Id=APKAJTEIOJM3LSMN33SA&Signature=WNKc53y3EwWzeodt2VlxRq0HKAYbSZfbYojlyxRinKHOAfcxsSRo6JG~JH2tTSSClGKdK85B3Z61w1j01O0L1URvSywrXaQ8z6h3e-TWYjhoiTofeqIEtew0y1qQpUV7tFq86q64Wvyu4p3NV2rBWeE9nogKyeG5NgIxH4uI6lE_)

Here's a link to the codebox so you can see which package versions I'm using. Perhaps there's a discrepancy here. 

[![Edit formik-antd/field-validation](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-cherry-rvn83?fontsize=14)

**Comment by jannikbuschke** [comment]
This is really weird. It seems that only the production build shows the behavior you are describing at that I also originally expected to be how it is meant to be.

I released preview 5, with the same implementation as in v0.12 (FormItem has no validation handler, all "core" antd-formik components have validation handlers)

It seems to work: https://codesandbox.io/s/formikantdfieldvalidation-yqj8k

@jwmann  can you also validate?


The weird thing is that I see a different behavior when using with lerna / locally linked setup.

**Comment by jwmann** [comment]
@jannikbuschke I can verify that your link seems to work.

Using the children render with props also seems to work if you pass the Formik Props as you mentioned.

[![Edit formik-antd/field-validation-as-children](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formikantdfieldvalidationaschildren-gwud8?fontsize=14)

I don't think we have to worry about the third case you mentioned:
```
<Formik><FormItem><Input/></FormItem></Formik>
```

As in literally every example that Formik's docs provides, it passes the props to the children
https://jaredpalmer.com/formik/docs/api/formik#children-reactreactnode-props-formikprops-values-reactnode

Or it uses the render prop.

Although rendering children without passing props 'works', I don't think it was ever intended to be used that way.

I think the best way to avoid issues is to document this requirement in our README so that new users might avoid this edge case

**Comment by jannikbuschke** [comment]
I guess it wasnt intended that way as in normal formik forms usually the props that are handed in are required to implement the form.

I like the non-function/pure declarative form the most (for the majority of simple forms) as it is the most minimalist one. Also this is library embraces this very declarative style.

But it is fine I guess, I will update the docs accordingly.
