### ISSUE TITLE
Allow Formik 2

### ISSUE THREAD

**Issue by Khartir** [jannikbuschke/formik-antd#91]
Formik 2 is nearing completion and as far as I can tell, there is no reason that formik-antd should not simply work with Formik 2. I did some tests on a project I'm working on and it seems to be working just fine. So I would suggest to increase the allowed Formik version.

**Comment by jannikbuschke** [comment]
My tests so far also work. However I would like to wait until formik v2 is final.

**Comment by rszemplinski** [comment]
Looks like it came out yesterday

**Comment by jannikbuschke** [comment]
you can start using https://www.npmjs.com/package/formik-antd (instead of `@jbuschke/formik-antd` use `formik-antd`) with version 1.6. It should state compatibility with formik v2.

I didnt yet properly announce the new namespace, however all future versions will be land on this new namespace/package.
